version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trutrend_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  trutrend-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/trutrend_dev
      - DEBUG=true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - /tmp/trutrend_uploads:/tmp/trutrend_uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: