[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m uvicorn simple_analyzer:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PORT = "8000"
PYTHONPATH = "."