services:
  - type: web
    name: trutrend-diabetes-analytics
    env: python
    runtime: python-3.11.6
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m uvicorn simple_analyzer:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health